# Generated by Django 6.1 on 2026-08-18 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Orchid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('size', models.CharField(blank=True, max_length=50)),
                ('care_level', models.CharField(blank=True, max_length=50)),
                ('light_requirement', models.CharField(blank=True, max_length=100)),
                ('watering_frequency', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OUT_OF_STOCK', 'Out of Stock'), ('INACTIVE', 'Inactive')], default='AVAILABLE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orchids', to='products.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
