# Generated by Django 6.1 on 2026-08-18 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrchidImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('orchid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.orchid')),
            ],
            options={
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
    ]
